    procedure emit_$$ 
      
    :
      call enqueue_$$(@parameter0,@parameter1);
      call step_$$();
      spec {((@current_automaton_state!="HasNexterror"))}()
        {((@current_automaton_state!="HasNexterror"))};
    procedure step_$$ 
      {()}
      (@current_queue_list_size,@current_automaton_state,@register_i
      ,@current_queue_list_size)
      {((@register_i=_log_register_i_2_trans_1)
       *(@current_automaton_state="HasNextvalid")
       *(@current_queue_list_size="0"))
      }+{()}
      (@current_queue_list_size,@current_automaton_state,@register_i
      ,@current_queue_list_size,@queue_event_0_position_1
      ,@queue_event_0_position_0)
      {((@queue_event_0_position_1=_log_queue_1_1)
       *(@queue_event_0_position_0=_log_queue_1_0)
       *(@current_automaton_state="HasNexterror")
       *(@register_i=_log_register_i_1_trans_0)
       *(@current_queue_list_size="1"))
      }+{()}
      (@current_queue_list_size,@current_automaton_state,@register_i
      ,@current_queue_list_size,@current_queue_list_size
      ,@current_automaton_state,@register_i,@current_queue_list_size
      ,@queue_event_0_position_1,@queue_event_0_position_0)
      {(((@register_i=_log_register_i_2_trans_1)
        *(@current_automaton_state="HasNextvalid")
        *(@current_queue_list_size="0"))
       ||((@queue_event_0_position_1=_log_queue_1_1)
         *(@queue_event_0_position_0=_log_queue_1_0)
         *(@current_automaton_state="HasNexterror")
         *(@register_i=_log_register_i_1_trans_0)
         *(@current_queue_list_size="1"))
       )
      }+{()}
      (@current_queue_list_size,@current_automaton_state,@register_i
      ,@current_queue_list_size,@queue_event_0_position_1
      ,@queue_event_0_position_0)
      {((@queue_event_0_position_1=_log_queue_1_1)
       *(@current_automaton_state="HasNextinvalid")
       *(@queue_event_0_position_0=_log_queue_1_0)
       *(@register_i=_log_register_i_1_trans_0)
       *(@current_queue_list_size="1"))
      }+{()}
      (@current_queue_list_size,@register_i,@current_queue_list_size
      ,@queue_event_0_position_1,@queue_event_0_position_0
      ,@current_queue_list_size,@current_automaton_state,@register_i
      ,@current_queue_list_size,@queue_event_0_position_1
      ,@queue_event_0_position_0)
      {(((@current_automaton_state="HasNextstart")
        *(@queue_event_0_position_1=_log_queue_1_1)
        *(@queue_event_0_position_0=_log_queue_1_0)
        *(@register_i=_log_register_i_1_trans_1)
        *(@current_queue_list_size="1"))
       ||((@queue_event_0_position_1=_log_queue_1_1)
         *(@current_automaton_state="HasNextinvalid")
         *(@queue_event_0_position_0=_log_queue_1_0)
         *(@register_i=_log_register_i_1_trans_0)
         *(@current_queue_list_size="1"))
       )
      }
      +{((@current_queue_list_size="2")
        *(@queue_event_1_position_1=_log_queue_1_1)
        *(@register_i=_log_register_i_0)
        *(@queue_event_1_position_0=_log_queue_1_0)
        *(@current_automaton_state="HasNextstart")
        *(@queue_event_0_position_1=_log_queue_0_1)
        *(@queue_event_0_position_0=_log_queue_0_0))
       }
      (@current_queue_list_size,@queue_event_0_position_1
      ,@queue_event_0_position_0)
      {((@current_automaton_state="HasNextstart")
       *(@register_i=_log_register_i_0)
       *(@queue_event_0_position_1=_log_queue_1_1)
       *(@queue_event_0_position_0=_log_queue_1_0)
       *(@current_queue_list_size="1"))
      }
      +{(((@register_i=_log_register_i_0)*(@current_queue_list_size="2")
         *(@queue_event_0_position_0=_log_queue_0_0)
         *(@queue_event_0_position_1=_log_queue_0_1)
         *(@queue_event_1_position_0=_log_queue_1_0)
         *(@queue_event_1_position_1=_log_queue_1_1)
         *(@current_automaton_state="HasNextinvalid")
         *(_log_register_i_1_trans_1=_log_register_i_0))
        ||((@queue_event_0_position_0=_log_queue_0_0)
          *(@queue_event_1_position_1=0)
          *(@queue_event_0_position_1=_log_queue_0_1)
          *(@register_i=_log_register_i_0)
          *(@current_automaton_state="HasNextinvalid")
          *(@queue_event_1_position_0=_log_queue_1_0)
          *(@current_queue_list_size="2")
          *(@queue_event_1_position_1=_log_queue_1_1)
          *(_log_register_i_1_trans_1=_log_register_i_0))
        ||((@queue_event_0_position_1!=_log_register_i_0)
          *(@queue_event_0_position_0=_log_queue_0_0)
          *(@queue_event_0_position_1=_log_queue_0_1)
          *(@register_i=_log_register_i_0)
          *(@current_automaton_state="HasNextinvalid")
          *(@queue_event_1_position_0=_log_queue_1_0)
          *(@queue_event_1_position_1=_log_queue_1_1)
          *(@current_queue_list_size="2")
          *(_log_register_i_1_trans_1=_log_register_i_0))
        ||((@register_i=_log_register_i_0)
          *(@current_automaton_state="HasNextinvalid")
          *(@queue_event_0_position_1!=_log_register_i_0)
          *(@queue_event_1_position_1=0)
          *(@queue_event_1_position_1=_log_queue_1_1)
          *(@queue_event_0_position_1=_log_queue_0_1)
          *(@current_queue_list_size="2")
          *(@queue_event_1_position_0=_log_queue_1_0)
          *(@queue_event_0_position_0=_log_queue_0_0)
          *(_log_register_i_1_trans_1=_log_register_i_0))
        ||((@current_queue_list_size="2")
          *(@queue_event_1_position_1=_log_queue_1_1)
          *(@register_i=_log_register_i_0)
          *(@queue_event_1_position_0=_log_queue_1_0)
          *(@current_automaton_state="HasNextinvalid")
          *(@queue_event_0_position_1=_log_queue_0_1)
          *(@queue_event_0_position_0=_log_queue_0_0))
        ||((@register_i=_log_register_i_0)*(@current_queue_list_size="2")
          *(@queue_event_0_position_1=_log_queue_0_1)
          *(@queue_event_0_position_0=_log_queue_0_0)
          *(@queue_event_1_position_1=_log_queue_1_1)
          *(@queue_event_1_position_0=_log_queue_1_0)
          *(@queue_event_0_position_1!=_log_register_i_0)
          *(@current_automaton_state="HasNextinvalid"))
        ||((@register_i=_log_register_i_0)*(@current_queue_list_size="2")
          *(@queue_event_0_position_0=_log_queue_0_0)
          *(@queue_event_0_position_1=_log_queue_0_1)
          *(@queue_event_0_position_1!=_log_register_i_0)
          *(@queue_event_1_position_0=_log_queue_1_0)
          *(@queue_event_1_position_1=_log_queue_1_1)
          *(@current_automaton_state="HasNextinvalid"))
        )
       }
      (@current_queue_list_size,@queue_event_0_position_1
      ,@queue_event_0_position_0)
      {((@register_i=_log_register_i_0)
       *(@queue_event_0_position_1=_log_queue_1_1)
       *(@current_automaton_state="HasNextinvalid")
       *(@queue_event_0_position_0=_log_queue_1_0)
       *(@current_queue_list_size="1"))
      }
      +{(((@register_i=_log_register_i_0)*(@current_queue_list_size="2")
         *(@queue_event_0_position_1=_log_queue_0_1)
         *(@queue_event_0_position_0=_log_queue_0_0)
         *(@current_automaton_state="HasNextvalid")
         *(@queue_event_1_position_1=_log_queue_1_1)
         *(@queue_event_1_position_0=_log_queue_1_0)
         *(@queue_event_0_position_1!=_log_register_i_0))
        ||((@current_queue_list_size="2")
          *(@queue_event_1_position_1=_log_queue_1_1)
          *(@register_i=_log_register_i_0)
          *(@queue_event_1_position_0=_log_queue_1_0)
          *(@queue_event_0_position_1=_log_queue_0_1)
          *(@current_automaton_state="HasNextvalid")
          *(@queue_event_0_position_0=_log_queue_0_0))
        )
       }
      (@current_queue_list_size,@queue_event_0_position_1
      ,@queue_event_0_position_0)
      {((@register_i=_log_register_i_0)
       *(@queue_event_0_position_1=_log_queue_1_1)
       *(@queue_event_0_position_0=_log_queue_1_0)
       *(@current_automaton_state="HasNextvalid")
       *(@current_queue_list_size="1"))
      }
      +{((@current_queue_list_size="2")
        *(@current_automaton_state="HasNexterror")
        *(@queue_event_1_position_1=_log_queue_1_1)
        *(@register_i=_log_register_i_0)
        *(@queue_event_1_position_0=_log_queue_1_0)
        *(@queue_event_0_position_1=_log_queue_0_1)
        *(@queue_event_0_position_0=_log_queue_0_0))
       }
      (@current_queue_list_size,@queue_event_0_position_1
      ,@queue_event_0_position_0)
      {((@register_i=_log_register_i_0)
       *(@queue_event_0_position_1=_log_queue_1_1)
       *(@queue_event_0_position_0=_log_queue_1_0)
       *(@current_automaton_state="HasNexterror")
       *(@current_queue_list_size="1"))
      }+{()}
      (@current_queue_list_size,@register_i,@current_queue_list_size
      ,@queue_event_0_position_1,@queue_event_0_position_0)
      {((@current_automaton_state="HasNextstart")
       *(@queue_event_0_position_1=_log_queue_1_1)
       *(@queue_event_0_position_0=_log_queue_1_0)
       *(@register_i=_log_register_i_1_trans_1)
       *(@current_queue_list_size="1"))
      }
    procedure enqueue_$$ 
      {(@current_queue_list_size="0")}
      (@current_queue_list_size,@queue_event_0_position_0
      ,@queue_event_0_position_1)
      {((@current_queue_list_size="1")
       *(@queue_event_0_position_0=@parameter0)
       *(@queue_event_0_position_1=@parameter1))
      }+{(@current_queue_list_size="1")}
      (@current_queue_list_size,@queue_event_1_position_0
      ,@queue_event_1_position_1)
      {((@current_queue_list_size="2")
       *(@queue_event_1_position_0=@parameter0)
       *(@queue_event_1_position_1=@parameter1))
      }
